remotes::install_github("r-lib/rlang")
devtools::install_github("r-lib/vctrs")
remotes::install_github("r-lib/lifecycle")
devtools::install_github("tidyverse/tidyr")
devtools::install_github("thomasp85/patchwork")
install.packages("ggrepel", repos="http://cran.rstudio.com")
install.packages("gapminder", repos="http://cran.rstudio.com")
install.packages("plotly", repos="http://cran.rstudio.com")
install.packages("sf", repos="http://cran.rstudio.com")
install.packages("ggmap", repos="http://cran.rstudio.com")
install.packages("here", repos="http://cran.rstudio.com")
install.packages("geojsonio", repos="http://cran.rstudio.com")
